# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGpsSimulator < Formula
  desc "GPS NMEA0183 Simulator - Command-line tool for simulating GPS receiver output"
  homepage "https://github.com/Bucknalla/go-gps-simulator"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.4/go-gps-simulator_Darwin_x86_64.tar.gz"
      sha256 "5970f06e9af8cdcc79b21364cdc3d48761e04a527b64ce246e956bac26366efb"

      def install
        bin.install "gps-simulator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.4/go-gps-simulator_Darwin_arm64.tar.gz"
      sha256 "e143c37ca2dfaad498cbae8d373e57df5eab86bb790a1bf62a54ded88cd979f0"

      def install
        bin.install "gps-simulator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.4/go-gps-simulator_Linux_x86_64.tar.gz"
      sha256 "cd4a914679c5beb2fff334627a17970dda2bdf5da0f2cd2bcc9453d7f4632796"
      def install
        bin.install "gps-simulator"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.4/go-gps-simulator_Linux_armv6.tar.gz"
      sha256 "652a895a8542b47a0561baadbd7ed015634c08778ab3a4c25667d022a07a38d3"
      def install
        bin.install "gps-simulator"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.4/go-gps-simulator_Linux_arm64.tar.gz"
      sha256 "1c8a105a38a3a5bf2e451b1022ddce0b42b41bc6dacd1b06b9a40205df1e140d"
      def install
        bin.install "gps-simulator"
      end
    end
  end

  test do
    system "#{bin}/gps-simulator", "-version"
  end
end
