# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGpsSimulator < Formula
  desc "GPS NMEA0183 Simulator - Command-line tool for simulating GPS receiver output"
  homepage "https://github.com/Bucknalla/go-gps-simulator"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.2/go-gps-simulator_Darwin_x86_64.tar.gz"
      sha256 "c0c4f82e9d24f41af10bace4c28518979aeae3f0d5534451848c3f9e2b7f90b9"

      def install
        bin.install "gps-simulator"
        pkgshare.install "scripts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.2/go-gps-simulator_Darwin_arm64.tar.gz"
      sha256 "8a0822815d973b1615cf163dc24d56eeac17f83c2ba0d754bb4afaf5ad7f10b1"

      def install
        bin.install "gps-simulator"
        pkgshare.install "scripts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.2/go-gps-simulator_Linux_x86_64.tar.gz"
      sha256 "cd6f3e3bd2aa70a7c3aca82d9171db34851d5c3b9711e9db1c155bcb5bfd73f5"
      def install
        bin.install "gps-simulator"
        pkgshare.install "scripts"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.2/go-gps-simulator_Linux_armv6.tar.gz"
      sha256 "90e8c82098b1038e1390cb1bbf5bb6e234e6783a07c808219f29fe4c2da23b57"
      def install
        bin.install "gps-simulator"
        pkgshare.install "scripts"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.2/go-gps-simulator_Linux_arm64.tar.gz"
      sha256 "ea16b919c9a8119d1becd4a8d338748e9cd325a197bb5592364bc8a72708d6c7"
      def install
        bin.install "gps-simulator"
        pkgshare.install "scripts"
      end
    end
  end

  test do
    system "#{bin}/gps-simulator", "-version"
  end
end
