# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GpsSimulator < Formula
  desc "GPS NMEA0183 Simulator - Command-line tool for simulating GPS receiver output"
  homepage "https://github.com/Bucknalla/go-gps-simulator"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.8/go-gps-simulator_Darwin_x86_64.tar.gz"
      sha256 "8791109a8569d183f5901fcff3c97d23c5fbbf487ffbdfcc202d7af354d9be2b"

      def install
        bin.install "gps-simulator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.8/go-gps-simulator_Darwin_arm64.tar.gz"
      sha256 "36894db367ec38591d660038b7454603c43e913edebb6a4ba89548041ad20b09"

      def install
        bin.install "gps-simulator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.8/go-gps-simulator_Linux_x86_64.tar.gz"
      sha256 "3c3a0e572682313df18c953ff29e9caeaaf8e74e2bf8ab51b54def8060eea3d8"
      def install
        bin.install "gps-simulator"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.8/go-gps-simulator_Linux_armv6.tar.gz"
      sha256 "4196da9fa7dcf361301ed5019c560c2eb873b015b25516acccb737bace395bab"
      def install
        bin.install "gps-simulator"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.8/go-gps-simulator_Linux_arm64.tar.gz"
      sha256 "7579e808235e4a7d97c80c32b0cbd06c37bd2ea4885a3ff9de4ca64fcfc4daad"
      def install
        bin.install "gps-simulator"
      end
    end
  end

  test do
    system "#{bin}/gps-simulator", "-version"
  end
end
