# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GpsSimulator < Formula
  desc "GPS NMEA0183 Simulator - Command-line tool for simulating GPS receiver output"
  homepage "https://github.com/Bucknalla/go-gps-simulator"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.5/go-gps-simulator_Darwin_x86_64.tar.gz"
      sha256 "7b882163218cd7a2af8fafaf5ca47eec3bd4a7e1bbb54dfa7d50d45e04e9443a"

      def install
        bin.install "gps-simulator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.5/go-gps-simulator_Darwin_arm64.tar.gz"
      sha256 "939010a86773940cc3b6c741bc8da08ee41581e020646f3bc656767d19f1e732"

      def install
        bin.install "gps-simulator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.5/go-gps-simulator_Linux_x86_64.tar.gz"
      sha256 "7efd69ea4c128e677c690f6374602145add1870077c9275a495536df03c92f3e"
      def install
        bin.install "gps-simulator"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.5/go-gps-simulator_Linux_armv6.tar.gz"
      sha256 "53408ab9ab9d87a88683864a408fcf26ae70a2e057b34a592e348f8191d049e3"
      def install
        bin.install "gps-simulator"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Bucknalla/go-gps-simulator/releases/download/v0.0.5/go-gps-simulator_Linux_arm64.tar.gz"
      sha256 "65f5c114f6e36e66621d8a1117c907d6dea09c58829973f908da3db80d5492f0"
      def install
        bin.install "gps-simulator"
      end
    end
  end

  test do
    system "#{bin}/gps-simulator", "-version"
  end
end
